### ISSUE TITLE
Bug with the paint swatches, for car paint, menu colors.

### ISSUE THREAD

**Issue by qwertyuiopBB10** [NativeFunction/GTA-V-Console-RAGE-Script-ASM-Menu#1]
There seems to be a issue with the menu terminating when you try to change the menu base colors. Or if you try to change vehicle primary/secondary colors,  It will show the paint swatches for 1 second, then the menu terminates itself. Just thought I should let you know about this issue, just in case it was a unknown bug, & so that it could possibly be fixed. --- Thanks.

**Comment by NativeFunction** [comment]
You're starting the script with too low of a stack size, try 2048.

**Comment by gatekeeper1122** [comment]
what does stack size have todo with the color part of the menu from crashing exactly?

**Comment by qwertyuiopBB10** [comment]
Thanks for the heads up there. I'm by no means a developer of any sort. So that is something I have 0 clue on how to fix. I'm a user of the menu only, & I have to say the menu is extremely nice. So thanks a ton for the release here, I'm having a blast using it in SP. If anyone with knowledge on how to fix what the op of this menu has just pointed out, & could contribute a release with the fix for the color/paint menu. Would be great & extremely appreciated. -- Thanks again to anyone here that would be willing to fix it.

**Comment by NativeFunction** [comment]
@gatekeeper1122 
The function draw_color_pallet_to_get_color_index has 200 local vars and pushes a max of 70 totaling in 1080 bytes so if you start the script like `start_new_script("Script", 1024);` it won't work.

@qwertyuiopBB10 
Start the script with a stack size of 2048 >  `start_new_script("Script", 2048);` .

**Comment by qwertyuiopBB10** [comment]
How would I go about doing that exactly?. If you don't mind me asking. Would this require me to make changes to the script.xsa that is posted here? . Again, sorry if I'm abit (...alot) noobish when it comes to this...... & I'm still sort of (...alot) struggling to understand what I exactly need to do to make it work. Does it require me to make changes to the menu source file itself?, or if it could be something much more simple that I'm not following, so that I can just change the stack size of the script while in game ?.  < Any & all insight on that would be really great. Thank you.

**Comment by qwertyuiopBB10** [comment]
Alright,  so from what I now understand. You're talking about having a modloader load the script with the stack size as 2048. Instead of 1024. (If this is what you mean.) I actually had no clue what you meant previously, as I'm not familiar with creating/editing scripts. But I will try this on a open source modloader. Will keep you posted. Thanks again for the great release here.

**Comment by qwertyuiopBB10** [comment]
Just a tiny update with my results here.... I did try to re compile a modloader source (tustins asm loader) with the stack size changed from 1024 > 2048 for the input custom script function. Sadly, there was issue with the modloader for me, causing a freeze on my console. (It's possible that the modloader has ps3 only functions coded in.... That I didn't notice as I'm not to fluent in the scripting..) but I myself can't really confirm that was the reason behind the freeze. So I will just assume that is why I freeze when I enable it in game.  

I'm not sure if you would be willing to provide a working 360 version of any simple/basic script loader optimized for this menu, with the correct stack size for loading the script. If you could do that whenever you have the spare time on your hands, I would appreciate it a lot. As it would be extremely great to use the menu here with the full options, the paint selector, etc. Thanks again for the great release here.
