### ISSUE TITLE
Compiling Issue

### ISSUE THREAD

**Issue by Vicodin10** [NativeFunction/GTA-V-Console-RAGE-Script-ASM-Menu#2]
I noticed when this was first posted I would get and error during compile dealing with textcolor1 and so on, but if i compiled it for xbox then convert it to ps3 it would work. 
I re downloaded this a few days ago to play around with it more 
Now I can compile for ps3 without errors.
But either way I compile it now it gives my wrong color pallet when selecting menu colors ingame. 
Also highlight bar is black instead of white like it is originally.
It also messes with the warning messages. Like when enabling fly mode you receive a message showing you the binds.
Now the message is not wanting to show.

Has something changed in the source to cause this or is this just on my end?

**Comment by NativeFunction** [comment]
I never had that issue in my compiler. Try the rar download in the release tab for the xsc https://github.com/NativeFunction/GTA-V-Console-RAGE-Script-ASM-Menu/releases.

**Comment by Vicodin10** [comment]
So my conclusion
I started everything over on a different ext hdd
When i compile for ps3 i still dont get the error i use to get.
Compile for xbox or ps3 and load with correct stack size it still uses wrong color pallet.
Im not sure why i dont get the expected error anymore.


But all I was gonna do for now was use the message
Sorry, Not implemented yet. for the options that freeze on PS3.
But since it wont compile right even without altering stuff then im not sure.
Is there away you could compile a version for me maybe?

**Comment by NativeFunction** [comment]
Sounds like something is up with your compiler.
However the menu is not really for ps3, those options freeze because none of the memory addresses are correct.
If you want the script compiled for xbox you can download it here:
 https://github.com/NativeFunction/GTA-V-Console-RAGE-Script-ASM-Menu/releases.

**Comment by Vicodin10** [comment]
Well yeah I know why it freezes and all. I was attempting to update the addresses or at least the few I know.
 I do have the normal version working fine already.
I Just cant get an edited version to work right. But yeah thanks for the help though.
