### ISSUE TITLE
Compiling for the PC Version of GTA.

### ISSUE THREAD

**Issue by Duperdoogle** [NativeFunction/GTA-V-Console-RAGE-Script-ASM-Menu#4]
Hey would it be possible to compile this for the pc version of GTA V?. Thank you.

**Comment by NativeFunction** [comment]
It is possible, however, I do not have an ASM compiler to compile to YSC. The only compiler that supports YSC is SC-CL and with that, the native translation table would have to be updated. The only time I used the ASM menu on PC was on a custom VM made by njames93 which can be found [here](https://github.com/njames93/XSC-VM). Like SC-CL, the native translation would have to be updated [here](https://github.com/njames93/XSC-VM/blob/master/source/NativeTranslation.cpp).

**Comment by Duperdoogle** [comment]
Is there anyone I can contact that might be able to compile it to the .ysc format?.
I noticed there is a version of this menu floating around for The PS4 version.
Maybe it could be converted to .ysc? Thanks again for the response here.

**Comment by Duperdoogle** [comment]
Here is the menu on the PlayStation 4:
https://m.youtube.com/watch?v=F8GgeuOiRpU

Looks like it’s been updated to be compatible for current gen..

if you know who I could contact for who might be able to convert it would be highly appreciated. Would love to use this menu on sp on pc.

**Comment by Vicodin10** [comment]
> Here is the menu on the PlayStation 4: https://m.youtube.com/watch?v=F8GgeuOiRpU
> 
> Looks like it’s been updated to be compatible for current gen..
> 
> if you know who I could contact for who might be able to convert it would be highly appreciated. Would love to use this menu on sp on pc.

I can compile it, I have another version Ive yet to release, But its made for ps3/ps4/xbox addrs only.
So some features may not work on PC just by converting or compiling it the way it is.

**Comment by Duperdoogle** [comment]
If you could do that I would highly appreciate it. I can test it out on pc.

**Comment by Duperdoogle** [comment]
Loved using this menu back on on 360 with my Rgh. Would be cool to play with it on the pc platform.

**Comment by Vicodin10** [comment]
> If you could do that I would highly appreciate it. I can test it out on pc.

Can you message me on Discord?
Vicodin10#8882

Ill try to send you a copy tomorrow if thats ok.

**Comment by Duperdoogle** [comment]
Will do. Thank you for the help here.

my tag is: gamer8000#3983 
Sent you a request on discord as it won’t let me send you a message.

thanks again here.

**Comment by Duperdoogle** [comment]
> > If you could do that I would highly appreciate it. I can test it out on pc.
> 
> Can you message me on Discord? Vicodin10#8882
> 
> Ill try to send you a copy tomorrow if thats ok.

Hey are you available on discord?, am able to test a version out today if possible.
